// Pure domain data shared between the frontend (src/) and backend
// (server/, api/, prisma/seed.ts) — no framework dependencies, safe to
// import from either a Vite/React build or a plain Node script.

export const DEPARTMENTS = [
  'HR',
  'Housing',
  'IT',
  'Administration',
  'Security',
  'Transport',
  'Finance',
  'Medical',
  'Safety',
  'Electrical',
  'Mechanical',
  'Civil',
  'Purchase',
] as const

export type Department = (typeof DEPARTMENTS)[number]

export const GRIEVANCE_CATEGORIES = [
  'Attendance & Leave',
  'Career & Development',
  'Civil',
  'Compensation & benefits',
  'Compliance & Ethics',
  'Electrical',
  'Employee Relations',
  'HR Policies',
  'Recruitment & Onboarding',
  'Safety, Health & Environment (EHS)',
  'Security',
  'Separation & Exit',
  'Welfare & Engagement',
  'Facilities & Accommodation',
  'Harassment & Misconduct',
  'Housing & Quarters',
  'IT & HR System',
  'Medical & Insurance',
  'Payroll',
  'Performance Management',
  'Suggestion / Improvement',
  'Transport',
  'Club Facility',
  'Estate Maintenance',
  'Cleanliness & Housekeeping',
  'School & Education',
  'Temple',
] as const

export type GrievanceCategory = (typeof GRIEVANCE_CATEGORIES)[number]

export const CATEGORY_DEPARTMENT_MAP: Record<GrievanceCategory, Department> = {
  'Attendance & Leave': 'HR',
  'Career & Development': 'HR',
  'Civil': 'Civil',
  'Compensation & benefits': 'Finance',
  'Compliance & Ethics': 'HR',
  'Electrical': 'Electrical',
  'Employee Relations': 'HR',
  'HR Policies': 'HR',
  'Recruitment & Onboarding': 'HR',
  'Safety, Health & Environment (EHS)': 'Safety',
  'Security': 'Security',
  'Separation & Exit': 'HR',
  'Welfare & Engagement': 'HR',
  'Facilities & Accommodation': 'Administration',
  'Harassment & Misconduct': 'HR',
  'Housing & Quarters': 'Housing',
  'IT & HR System': 'IT',
  'Medical & Insurance': 'Medical',
  'Payroll': 'Finance',
  'Performance Management': 'HR',
  'Suggestion / Improvement': 'Administration',
  'Transport': 'Transport',
  'Club Facility': 'Housing',
  'Estate Maintenance': 'Housing',
  'Cleanliness & Housekeeping': 'Housing',
  'School & Education': 'Housing',
  'Temple': 'Housing',
}

export function getRoutedDepartment(category: GrievanceCategory): Department {
  return CATEGORY_DEPARTMENT_MAP[category] ?? 'Administration'
}

export const GRIEVANCE_SUBCATEGORIES: Record<GrievanceCategory, string[]> = {
  'Attendance & Leave': [
    'Attendance Correction',
    'Holiday Working',
    'Leave Balance',
    'Shift Issues',
  ],
  'Career & Development': [
    'Deputation',
    'Internal Job Posting (IJP)',
    'Job Rotation',
    'Learning Opportunity',
    'Promotion',
    'Training',
    'Transfer',
    'Others',
  ],
  'Civil': [
    'Building Repair',
    'Construction Issues',
    'Road/Darinage',
    'Others',
  ],
  'Compensation & benefits': [
    'Allowances',
    'Deputation Allowance',
    'GHI',
    'ESIC',
    'Bonus',
    'Gratuity',
    'Incentives',
    'Insurance',
    'PF',
    'Reimbursement',
    'Salary',
    'Others',
  ],
  'Compliance & Ethics': [
    'Conflict of Interest',
    'Corruption',
    'Dishonesty',
    'Ethics Violations',
    'Fraud',
    'Integraty',
    'Whistleblower Concerns',
    'Others',
  ],
  'Electrical': [
    'Equipment Fault',
    'Power Outage',
    'Wiring Issues',
    'Others',
  ],
  'Employee Relations': [
    'Conflict with Peers/Superior Authority',
    'Unfair Treatment',
    'Work Place Dispute',
    'Others',
  ],
  'HR Policies': [
    'Cement Concession',
    'Code of Conduct',
    'Policy Clarification',
    'Salary Advance',
    'Service Rules',
    'Others',
  ],
  'Recruitment & Onboarding': [
    'Documentation',
    'Induction',
    'Joining Formalities',
    'Probation',
    'Others',
  ],
  'Safety, Health & Environment (EHS)': [
    'Occupational Health',
    'PPE',
    'Safety Concerns',
    'Unsafe Conditions',
    'Others',
  ],
  'Security': [
    'Gate pass',
    'ID Card',
    'Theft/Loss Report',
    'Vehicle Entry',
    'Others',
  ],
  'Separation & Exit': [
    'Experience Letter',
    'Exit Interview',
    'FnF Sttlement',
    'NOC',
    'Notice Period',
    'Relieving Letter',
    'Resignation',
    'Superannuation',
    'Others',
  ],
  'Welfare & Engagement': [
    'Employee Engagement Activities',
    'Employee Welfare Schemes',
    'Events',
    'Recreation',
    'Others',
  ],
  'Facilities & Accommodation': [
    'Accomodation',
    'Cateen',
    'Guesthouse',
    'Houskeeping',
    'Security',
    'Transport',
    'Uniforms',
    'Others',
  ],
  'Harassment & Misconduct': [
    'Bullying',
    'Discrimination',
    'Intimination',
    'Misconduct',
    'Sexual Harrasment',
    'Others',
  ],
  'Housing & Quarters': [
    'Electricity in Quarters',
    'Quarters Allotments',
    'Quarters Maintenance',
    'Water Supply',
    'Others',
  ],
  'IT & HR System': [
    'Attendance System',
    'ESS Issues',
    'HR4U Login',
    'Laptop',
    'Network',
    'Portal Access',
    'Software',
    'Others',
  ],
  'Medical & Insurance': [
    'Annual Health Check-ups',
    'Health Insurance',
    'Medical Reimbursement',
    'Network Hospitals',
    'Others',
  ],
  'Payroll': [
    'Arrears',
    'Final Settlement',
    'Payslip',
    'Recovery',
    'Salary Credit',
    'Tax Deduction',
    'Others',
  ],
  'Performance Management': [
    'Appraisal Concern',
    'Goal Setting',
    'KRA',
    'PMS',
    'Ratings',
    'Others',
  ],
  'Suggestion / Improvement': [
    'Policy Suggestions',
    'Process Improvement Ideas',
    'Workplace Improvements',
    'Others',
  ],
  'Transport': [
    'Bus Service',
    'Route Timing',
    'Transport Allowance',
    'Vehicle Condition',
    'Others',
  ],
  'Club Facility': [
    'Club Infrastructure & Maintenance',
    'Gymnasium',
    'Indoor Games',
    'Outdoor Games / Sports Facilities',
    'Swimming Pool',
    'Club House / Common Area',
    'Equipment / Assets',
    'Club Timing / Access',
    'Others',
  ],
  'Estate Maintenance': [
    'Road & Pavement Maintenance',
    'Leakage & Seepage',
    'Lift Issues',
    'Drainage & Sewerage',
    'Street Lights',
    'Garden & Landscaping',
    'Boundary Wall / Fencing',
    'Water Supply',
    'Electrical Maintenance',
    'Pest Control',
    'Waste Disposal',
    'Others',
  ],
  'Cleanliness & Housekeeping': [
    'Township Cleanliness',
    'Dog Issues',
    'Housekeeping Service',
    'Garbage Collection',
    'Sanitation',
    'Toilet / Washroom Cleanliness',
    'Drain Cleaning',
    'Pest / Insect Control',
    'Common Area Cleaning',
    'Club / Community Area Cleaning',
    'Others',
  ],
  'School & Education': [
    'School Infrastructure',
    'Classroom / Laboratory',
    'School Cleanliness',
    'Drinking Water / Sanitation',
    'School Bus Service',
    'Teacher / Staff Related',
    'Admission / Documentation',
    'Fee / Payment Related',
    'Academic / Examination',
    'Quality of Education',
    'Effectiveness of PTM',
    'Sports & Extracurricular Activities',
    'Student Discipline & Behaviour',
    'School Administration',
    'Student Safety & Security',
  ],
  'Temple': [
    'Prayer / Worship Facilities',
    'Puja / Ritual Arrangements',
    'Priest / Pujari Related',
    'Temple Timings',
    'Festival & Religious Events',
    'Sound System / Announcements',
    'Seating & Common Area',
    'Security & Safety',
    'Parking / Access',
    'Temple Infrastructure',
    'Suggestions for Improvement',
    'Others',
  ],
}
